allowBuilds:
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
overrides:
  '@hono/node-server@<1.19.13': '>=1.19.13'
